stages:
  - build

addReadme:
  stage: build
  script:
    - echo "This is a README file" > README.md
    - git config user.email "you@example.com"
    - git config user.name "Your Name" 
    - git add README.md
    - git commit -m "Add README.md"
    - git push
