---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ELBListenerRuleProvider:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cfn-listener-rule-provider
      Handler: index.lambda_handler
      Timeout: 30
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.6
      Code:
        S3Bucket: !Sub 'binx-io-public-${AWS::Region}'
        S3Key: lambdas/cfn-listener-rule-provider-0.1.0.zip

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: elb-listener-rule-provider
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:CreateRule
                  - elasticloadbalancing:DeleteRule
                  - elasticloadbalancing:ModifyRule
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*
