---
name: release-to-pypi
"on":
  push:
    tags:
      - '*'
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: checkout
        run: git fetch --prune --unshallow
      - name: install environment
        run: pip install pipenv
      - name: run tests
        run: make test
      - name: release
        run: make snapshot
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
